
function Inversiones() {
  return (
    <section className="padded">
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ipsam fugiat, quidem quasi doloremque temporibus quia praesentium nostrum incidunt? Saepe esse eligendi recusandae minima, ratione temporibus quasi ducimus doloribus distinctio necessitatibus ab accusamus non dolores delectus repudiandae eius error. Culpa praesentium voluptatem minus vero ullam numquam, quasi rerum, explicabo quidem eaque necessitatibus illum. Commodi facere, animi dolorem velit quisquam recusandae reiciendis porro consequatur ipsam magnam alias labore! Beatae dolorum dignissimos tempore corporis voluptatum. At, est natus quo totam quis rerum?</p>
                <p>Aliquam alias vel commodi repellendus nemo soluta optio numquam harum temporibus accusamus molestiae, dolorem ab ad corrupti excepturi sed quibusdam sapiente omnis sequi doloremque fugit doloribus nisi esse? Neque, distinctio. A aspernatur laboriosam totam nemo aliquam excepturi, incidunt nostrum sequi labore possimus iste officiis. Quibusdam, culpa porro labore laudantium similique nesciunt temporibus ducimus deserunt aperiam ab dolor quam, animi voluptatem enim dolorem consequatur? In soluta, consequuntur modi quae impedit distinctio nesciunt explicabo atque sequi reiciendis incidunt beatae officiis rem nisi.</p>
                <p>Qui consequuntur esse quas laboriosam iusto recusandae eveniet debitis dolorum voluptas ipsum repellendus, sit fugit quam, illum dicta distinctio inventore quibusdam est in voluptate, ea dolores maiores deleniti. Nulla nostrum esse neque! Aliquam voluptas numquam voluptates minus, asperiores quam ipsam delectus sunt molestiae suscipit dignissimos vitae perspiciatis, accusamus quisquam maxime ducimus culpa praesentium dolor quos iure aut ex quia temporibus ratione? Expedita deleniti reiciendis officiis culpa eos laborum unde eveniet possimus. Incidunt eaque dignissimos dolores odio maiores libero beatae accusamus?</p>
                <p>Accusantium suscipit expedita quos obcaecati reiciendis vero consectetur in dignissimos vitae quam qui excepturi, magni doloremque autem maiores. Natus nobis odio, iusto, dolores, unde voluptatum sed explicabo voluptatibus aspernatur veritatis reiciendis delectus consequatur? Consequatur illo enim ut voluptas natus nam quia eveniet obcaecati. Nemo, fugit, expedita iusto maiores eaque, doloremque illo incidunt perspiciatis quam nam nostrum! Cumque nesciunt incidunt officiis esse, tenetur deserunt quaerat. Asperiores sed, libero ullam, minus obcaecati dolorum culpa laudantium delectus neque, quae sint ut quos labore!</p>
                <p>Perspiciatis in ratione eos vel molestias delectus sit laborum itaque similique, iste nam voluptatum sed iure. Rerum, eligendi consequuntur. Ipsum non, voluptatibus cupiditate, blanditiis quia reiciendis animi ea natus veritatis provident ipsam autem sunt pariatur? Eius, rem maxime dolore assumenda sed laborum ad architecto ex reiciendis, ducimus eaque obcaecati vel nihil? Sed earum expedita, voluptatibus quaerat minima et praesentium temporibus quibusdam assumenda, libero, velit dolores magnam cupiditate explicabo. Numquam voluptatibus a nostrum voluptatum quibusdam omnis sint cumque excepturi unde inventore?</p>
                <p>Iure omnis dolorem eaque quam perspiciatis praesentium, sit quidem dolorum! Consectetur dolor vitae ipsa magni nam, laudantium cum minima assumenda odit rerum inventore ducimus corrupti voluptatum ipsam molestiae? Eaque dolor iusto, eveniet voluptates facilis modi odit eligendi quod distinctio animi vel voluptas laboriosam minus dolore. Dolorum beatae sapiente voluptates qui necessitatibus, et minima nam, perspiciatis alias deserunt nulla eos. Possimus similique nisi natus et aut ex temporibus quas, fuga necessitatibus nemo. Unde dolorem vel laboriosam necessitatibus enim. Aperiam, aliquid inventore.</p>
            </div>
        </section>
  )
}

export default Inversiones